from . import kurs_qushish
from . import kursni_ochirish
from . import statistika
from . import remove_admin
from . import user_id_reklama
from . import user_all_reklama
from . import kursni_tah
from . import other
from . import admin