# Generated by Django 5.1.3 on 2024-12-13 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Kurs nomi')),
                ('tarif', models.TextField(verbose_name="Kursga ta'rif bering")),
            ],
            options={
                'verbose_name': '2.  Kurslar',
                'verbose_name_plural': '2.  Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Obunachilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Foydalanuvchi username')),
                ('full_name', models.CharField(max_length=150, null=True, verbose_name='Foydalanuvchining ismi')),
                ('phone_num', models.CharField(max_length=15, null=True, unique=True, verbose_name='Telefon raqami')),
                ('admin', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский')], default='uz', max_length=2, verbose_name='Til')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID ')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '3.  Obunachilar',
                'verbose_name_plural': '3.  Obunachilar',
            },
        ),
        migrations.CreateModel(
            name='Statistika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_subscribers', models.IntegerField(verbose_name='Barcha obunachilar')),
                ('for_last_month', models.IntegerField(verbose_name='Oxirgi oyda qushilganlar')),
                ('latest_news_readers', models.IntegerField(verbose_name="Oxirgi xabar necha kishiga jo'natilgan")),
            ],
            options={
                'verbose_name': '1.  Statistika',
                'verbose_name_plural': '1.   Statistika',
            },
        ),
        migrations.CreateModel(
            name='Xabar_yuborish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50, verbose_name='Xabar turi')),
                ('content', models.TextField(verbose_name="Matn, video yoki rasm uchun link jo'nating")),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('send_to_all', models.IntegerField(default=False)),
                ('obunachilar', models.ManyToManyField(blank=True, to='informations.obunachilar')),
            ],
            options={
                'verbose_name': '4.  Xabarlar',
                'verbose_name_plural': '4.   Xabarlar',
            },
        ),
        migrations.CreateModel(
            name='Malumotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admins', models.IntegerField()),
                ('last_message_sent_date', models.DateTimeField(null=True)),
                ('latest_news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='informations.xabar_yuborish')),
            ],
            options={
                'verbose_name': '6.  Malumotlar',
                'verbose_name_plural': '6.   Malumotlar',
            },
        ),
    ]
