# Generated by Django 5.1.4 on 2024-12-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kurslar',
            options={'verbose_name': '2. Kurslar', 'verbose_name_plural': '2. Kurslar'},
        ),
        migrations.AddField(
            model_name='kurslar',
            name='matn',
            field=models.TextField(blank=True, null=True, verbose_name='Kurs uchun matn'),
        ),
        migrations.AddField(
            model_name='kurslar',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='kurslar_rasmlari/', verbose_name='Kurs rasmi'),
        ),
    ]
