# Generated by Django 5.1.4 on 2024-12-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0003_obunachilar_last_active_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malumotlar',
            name='latest_news',
        ),
    ]
