# Generated by Django 5.1.4 on 2024-12-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0004_remove_malumotlar_latest_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obunachilar',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский')], default='uz', max_length=15, verbose_name='Til'),
        ),
    ]
